# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\royal state\PycharmProjects\PYUIC-GUI-Converter-PyQt\EditorChoserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 346)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 290, 331, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 160, 246))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NotePadRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/notepad.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NotePadRadio.setIcon(icon)
        self.NotePadRadio.setIconSize(QtCore.QSize(24, 24))
        self.NotePadRadio.setChecked(True)
        self.NotePadRadio.setObjectName("NotePadRadio")
        self.verticalLayout.addWidget(self.NotePadRadio)
        self.NotePadppCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/notepad++.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NotePadppCheck.setIcon(icon1)
        self.NotePadppCheck.setObjectName("NotePadppCheck")
        self.verticalLayout.addWidget(self.NotePadppCheck)
        self.PythonIdleCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/idle.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PythonIdleCheck.setIcon(icon2)
        self.PythonIdleCheck.setObjectName("PythonIdleCheck")
        self.verticalLayout.addWidget(self.PythonIdleCheck)
        self.VSCodeCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/vscode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VSCodeCheck.setIcon(icon3)
        self.VSCodeCheck.setObjectName("VSCodeCheck")
        self.verticalLayout.addWidget(self.VSCodeCheck)
        self.VimCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/vim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VimCheck.setIcon(icon4)
        self.VimCheck.setObjectName("VimCheck")
        self.verticalLayout.addWidget(self.VimCheck)
        self.AtomCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/atom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AtomCheck.setIcon(icon5)
        self.AtomCheck.setObjectName("AtomCheck")
        self.verticalLayout.addWidget(self.AtomCheck)
        self.MSWordCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MSWordCheck.setIcon(icon6)
        self.MSWordCheck.setObjectName("MSWordCheck")
        self.verticalLayout.addWidget(self.MSWordCheck)
        self.NanoCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/nano.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NanoCheck.setIcon(icon7)
        self.NanoCheck.setObjectName("NanoCheck")
        self.verticalLayout.addWidget(self.NanoCheck)
        self.GeditCheck = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/gedit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GeditCheck.setIcon(icon8)
        self.GeditCheck.setIconSize(QtCore.QSize(24, 24))
        self.GeditCheck.setObjectName("GeditCheck")
        self.verticalLayout.addWidget(self.GeditCheck)
        self.SetButton = QtWidgets.QPushButton(Dialog)
        self.SetButton.setGeometry(QtCore.QRect(234, 210, 81, 41))
        self.SetButton.setObjectName("SetButton")
        self.restoreDefaultButton = QtWidgets.QPushButton(Dialog)
        self.restoreDefaultButton.setGeometry(QtCore.QRect(220, 150, 111, 31))
        self.restoreDefaultButton.setObjectName("restoreDefaultButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(190, 10, 171, 81))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 151, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Editor Chooser"))
        self.NotePadRadio.setText(_translate("Dialog", "NotePad"))
        self.NotePadppCheck.setText(_translate("Dialog", "NotePad++"))
        self.PythonIdleCheck.setText(_translate("Dialog", "Python IDLE"))
        self.VSCodeCheck.setText(_translate("Dialog", "Visual Studio Code"))
        self.VimCheck.setText(_translate("Dialog", "Vim"))
        self.AtomCheck.setText(_translate("Dialog", "Atom"))
        self.MSWordCheck.setText(_translate("Dialog", "Ms Word"))
        self.NanoCheck.setText(_translate("Dialog", "Nono"))
        self.GeditCheck.setText(_translate("Dialog", "Gedit"))
        self.SetButton.setText(_translate("Dialog", "Set"))
        self.restoreDefaultButton.setText(_translate("Dialog", "Reset To Default"))
        self.groupBox.setTitle(_translate("Dialog", "Editor Set To: "))
