# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ayieko/Projects And  Research/PycharmProjects/PYUIC-GUI-Converter-PyQt/FrontEnd.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 375)
        MainWindow.setMinimumSize(QtCore.QSize(700, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/mainIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 451, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 250, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ExecutableCheck = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.ExecutableCheck.setObjectName("ExecutableCheck")
        self.verticalLayout.addWidget(self.ExecutableCheck)
        self.AutoFillCkeck = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.AutoFillCkeck.setStatusTip("")
        self.AutoFillCkeck.setWhatsThis("")
        self.AutoFillCkeck.setObjectName("AutoFillCkeck")
        self.verticalLayout.addWidget(self.AutoFillCkeck)
        self.OpenAfterConvertionCheck = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.OpenAfterConvertionCheck.setToolTip("")
        self.OpenAfterConvertionCheck.setObjectName("OpenAfterConvertionCheck")
        self.verticalLayout.addWidget(self.OpenAfterConvertionCheck)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ConvertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ConvertButton.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConvertButton.setFont(font)
        self.ConvertButton.setObjectName("ConvertButton")
        self.horizontalLayout.addWidget(self.ConvertButton)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 681, 121))
        self.groupBox.setObjectName("groupBox")
        self.recentCombo = QtWidgets.QComboBox(self.groupBox)
        self.recentCombo.setGeometry(QtCore.QRect(80, 50, 491, 20))
        self.recentCombo.setMinimumSize(QtCore.QSize(341, 0))
        self.recentCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.recentCombo.setObjectName("recentCombo")
        self.FileNameEntry = QtWidgets.QLineEdit(self.groupBox)
        self.FileNameEntry.setGeometry(QtCore.QRect(80, 20, 591, 21))
        self.FileNameEntry.setMinimumSize(QtCore.QSize(451, 0))
        self.FileNameEntry.setObjectName("FileNameEntry")
        self.SearchSourceFileButton = QtWidgets.QPushButton(self.groupBox)
        self.SearchSourceFileButton.setGeometry(QtCore.QRect(600, 60, 71, 31))
        self.SearchSourceFileButton.setObjectName("SearchSourceFileButton")
        self.DestinationFileLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.DestinationFileLabel_2.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.DestinationFileLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DestinationFileLabel_2.setIndent(5)
        self.DestinationFileLabel_2.setObjectName("DestinationFileLabel_2")
        self.DestinationFileLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.DestinationFileLabel_3.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.DestinationFileLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DestinationFileLabel_3.setIndent(5)
        self.DestinationFileLabel_3.setObjectName("DestinationFileLabel_3")
        self.DestinationFileLabel_4 = QtWidgets.QLabel(self.groupBox)
        self.DestinationFileLabel_4.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.DestinationFileLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DestinationFileLabel_4.setIndent(5)
        self.DestinationFileLabel_4.setObjectName("DestinationFileLabel_4")
        self.freqCombo = QtWidgets.QComboBox(self.groupBox)
        self.freqCombo.setGeometry(QtCore.QRect(80, 80, 491, 20))
        self.freqCombo.setMinimumSize(QtCore.QSize(341, 0))
        self.freqCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.freqCombo.setObjectName("freqCombo")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(570, 50, 20, 51))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 681, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.SearchDestinationButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SearchDestinationButton.setGeometry(QtCore.QRect(610, 22, 61, 31))
        self.SearchDestinationButton.setObjectName("SearchDestinationButton")
        self.DestinationFileEntry = QtWidgets.QLineEdit(self.groupBox_2)
        self.DestinationFileEntry.setGeometry(QtCore.QRect(80, 20, 501, 21))
        self.DestinationFileEntry.setObjectName("DestinationFileEntry")
        self.DestinationFileLabel_5 = QtWidgets.QLabel(self.groupBox_2)
        self.DestinationFileLabel_5.setGeometry(QtCore.QRect(0, 20, 71, 21))
        self.DestinationFileLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DestinationFileLabel_5.setIndent(5)
        self.DestinationFileLabel_5.setObjectName("DestinationFileLabel_5")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(590, 20, 20, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFrequentFiles = QtWidgets.QMenu(self.menubar)
        self.menuFrequentFiles.setObjectName("menuFrequentFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Vrinda")
        font.setPointSize(10)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSetDefaultEditor = QtWidgets.QAction(MainWindow)
        self.actionSetDefaultEditor.setObjectName("actionSetDefaultEditor")
        self.actionFrequentFiles = QtWidgets.QAction(MainWindow)
        self.actionFrequentFiles.setObjectName("actionFrequentFiles")
        self.actionRecentFiles = QtWidgets.QAction(MainWindow)
        self.actionRecentFiles.setObjectName("actionRecentFiles")
        self.actionResetSources = QtWidgets.QAction(MainWindow)
        self.actionResetSources.setObjectName("actionResetSources")
        self.menuFile.addAction(self.actionSetDefaultEditor)
        self.menuFile.addAction(self.actionExit)
        self.menuFrequentFiles.addAction(self.actionFrequentFiles)
        self.menuFrequentFiles.addAction(self.actionRecentFiles)
        self.menuFrequentFiles.addSeparator()
        self.menuFrequentFiles.addAction(self.actionResetSources)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFrequentFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyuic GUI"))
        self.label.setText(_translate("MainWindow", "Convert A Ui file to a Python File"))
        self.ExecutableCheck.setStatusTip(_translate("MainWindow", "If Enabled Adds some Code to Make The Converted Ui File Executable"))
        self.ExecutableCheck.setWhatsThis(_translate("MainWindow", "Adds lines of code to make the file executable"))
        self.ExecutableCheck.setText(_translate("MainWindow", "Executable"))
        self.AutoFillCkeck.setText(_translate("MainWindow", "Auto Fill Destination"))
        self.OpenAfterConvertionCheck.setStatusTip(_translate("MainWindow", "Open The Python File In a Text Editor After Convertion Is complete"))
        self.OpenAfterConvertionCheck.setWhatsThis(_translate("MainWindow", "Adds lines of code to make the file executable"))
        self.OpenAfterConvertionCheck.setText(_translate("MainWindow", "Open After Convertion"))
        self.ConvertButton.setText(_translate("MainWindow", "Convert"))
        self.ConvertButton.setShortcut(_translate("MainWindow", "Return"))
        self.groupBox.setTitle(_translate("MainWindow", "Source"))
        self.FileNameEntry.setToolTip(_translate("MainWindow", "Full path to the destination"))
        self.FileNameEntry.setStatusTip(_translate("MainWindow", "Enter The full path to the destination of the converted python file"))
        self.SearchSourceFileButton.setText(_translate("MainWindow", "Search"))
        self.DestinationFileLabel_2.setText(_translate("MainWindow", "Recent"))
        self.DestinationFileLabel_3.setText(_translate("MainWindow", "File Path"))
        self.DestinationFileLabel_4.setText(_translate("MainWindow", "Frequent"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Destination"))
        self.SearchDestinationButton.setText(_translate("MainWindow", "Search"))
        self.DestinationFileEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Full path to the destination</p></body></html>"))
        self.DestinationFileEntry.setStatusTip(_translate("MainWindow", "Enter The full path to the destination of the converted python file"))
        self.DestinationFileLabel_5.setText(_translate("MainWindow", "File Path"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFrequentFiles.setTitle(_translate("MainWindow", "Sources"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSetDefaultEditor.setText(_translate("MainWindow", "Set Default Editor"))
        self.actionSetDefaultEditor.setToolTip(_translate("MainWindow", "Set Default Editor That opens the converted file"))
        self.actionFrequentFiles.setText(_translate("MainWindow", "Frequent Files"))
        self.actionRecentFiles.setText(_translate("MainWindow", "Resent Files"))
        self.actionResetSources.setText(_translate("MainWindow", "Reset Sources"))


